# Run first this command : source venv/bin/activate 
# Run : mkdocs serve
# Run : mkdocs build

# Project information
site_name: Documentazione
site_author: GURYOU
site_url: https://docs.guryou.com
site_description: >-
  Documentations for the platform YouDeal for Wellness Business

# Copyright
copyright: Copyright &copy; 2016 - 2023 GURYOU - TrantorMind s.r.l

# Configuration
theme: 
  name: material
  #custom_dir: material/.overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.prune
    - navigation.sections
  #  - navigation.tabs
  #  - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
#     # - toc.integrate
#  palette:
#    - scheme: slate
#      primary: 
#      accent: indigo
#      toggle:
#        icon: material/brightness-7
#        name: Switch to dark mode
#    - scheme: default
#      primary: indigo
#      accent: purple
#      toggle:
#        icon: material/brightness-4
#        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo:    assets/logo.png
  #icon:
  #  logo: logo
  language: it


# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks
# hooks:
#  - material/.overrides/hooks/translations.py


#extra:
#  alternate:
#    - name: English
#      link: /en/ 
#      lang: en
#    - name: Italiano
#      link: /it/
#      lang: it
#social:   
#  - icon: fontawesome/brands/github-alt
#    link: https://github.com/james-willett
#  - icon: fontawesome/brands/twitter
#    link: https://twitter.com/TheJamesWillett
#  - icon: fontawesome/brands/linkedin
#    link: https://www.linkedin.com/in/willettjames/

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - Benvenuto: index.md
  - Tour dettagliato: tour.md
  - Comincia subito:
    - Completa il tuo profilo: configuration-profile.md
 #   - Lancia un Servizio: customization.md
 #   - Lancia una Classe: philosophy.md